# Generated by Django 5.2.4 on 2026-03-26 01:40

import apis.utils.upload_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_director_pedagogico',
            field=models.ImageField(blank=True, null=True, upload_to=apis.utils.upload_utils.upload_to_custom, verbose_name='Assinatura do Director Pedagógico'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Expulso', 'Expulso'), ('Transferido', 'Transferido'), ('Suspenso', 'Suspenso'), ('Finalizou', 'Finalizou')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='assinatura_director',
            field=models.ImageField(blank=True, null=True, upload_to=apis.utils.upload_utils.upload_to_custom, verbose_name='Assinatura do Director Geral'),
        ),
        migrations.AlterField(
            model_name='solicitacaodocumento',
            name='status_solicitacao',
            field=models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('pago', 'Pago (Aguardando/Processando)'), ('disponivel', 'Concluído e Disponível'), ('rejeitado', 'Rejeitado / Cancelado')], default='pendente', max_length=30, verbose_name='Status'),
        ),
    ]
