# Generated by Django 5.2.4 on 2026-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_configuracaosistema_assinatura_director_pedagogico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='tipo_accao',
            field=models.TextField(editable=False, verbose_name='Ação Realizada'),
        ),
    ]
